version: "2" # required to adjust maintainability checks

checks:
  method-lines:
    enabled: true
    config:
      threshold: 25
  argument-count:
    enabled: true
    config:
      threshold: 3
exclude_patterns:
  - "test"
  - "test.py"
  - "test_**"
  - "test_*"
  - "**/test/"
  - "**/tests/"
  - "Tests/"