method-lines:
    config:
       threshold: 25
argument-count:
    config:
       threshold: 3
similar-code:
    config:
       threshold: 3
exclude_patterns:
- "test/"
- "/Users/mymac/Documents/computacion 2022 github personal/parcial-2-2022-Lucasgarciamdz/test/*"
exclude_paths:
- "test.py"
